name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        # Or use npm:
        # run: npm install

      - name: Build Strapi app
        run: yarn build
        # Or use npm:
        # run: npm run build

      - name: Clone repository on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone https://github.com/priyanka-1994/Task-2-Pearthought-StrapiApp.git

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Task-2-Pearthought-StrapiApp
            git pull origin main
            yarn install --frozen-lockfile --production
            yarn start
            # Or use npm:
            # npm install --production
            # npm start

