name: Deploying Strapi App on EC2 Using Github Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install Yarn
      run: npm install -g yarn

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo apt-get update -y
          sudo apt-get install -y nodejs npm git
          sudo npm install -g yarn
          if [ ! -d "/home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp" ]; then
            git clone https://github.com/priyanka-1994/Task-2-Pearthought-StrapiApp.git /home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp
          else
            cd /home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp && git pull
          fi

          cd /home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp
          ls
          cd priya-strapi-app-task-2
          yarn install
          npm run build
          
          yarn build
          yarn develop

    - name: Success
      if: success()
      run: echo "Deployment successful!"

    - name: Alerting About Failure
      if: failure()
      run: echo "Deployment failed!"

