name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Strapi
        run: sudo npm install strapi -g
      - name: Install pm2
        run: sudo npm install -g pm2
        

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
        
          script: |
            sudo apt-get update -y
            sudo apt-get install -y nodejs npm git
           
            REPO_DIR="/home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp"
            # Clone or update repository
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/priyanka-1994/Task-2-Pearthought-StrapiApp.git $REPO_DIR
            else
              cd $REPO_DIR
              git fetch --all
              git reset --hard origin/main
              git pull origin main
            fi
            # Remove 'new-strapi' directory if exists and not empty
            if [ -d "$REPO_DIR/new-project" ]; then
              rm -rf $REPO_DIR/new-project
            fi
            # Create new Strapi app in 'new-project' directory
            cd $REPO_DIR 
            yarn install
            npm run build

            yarn create strapi-app new new-project--quickstart
            rm -rf /home/ubuntu/Task-2-Pearthought-StrapiApp/yarn.lock
            rm -rf /home/ubuntu/Task-2-Pearthought-StrapiApp/package.json
            cd new-project
            # touch /home/ubuntu/Task-2-Pearthought-StrapiApp/new-project/yarn.lock
            
            yarn install
            #touch /home/ubuntu/Task-2-Pearthought-StrapiApp/new-project/yarn.lock
            yarn build
            yarn develop
            #strapi new new-project --quickstart
            #cd $REPO_DIR/new-project && npm install 
            
            
            npm cache clean --force
        
            # Start Strapi app with PM2
            #pm2 start yarn --name "strapi" -- run develop
            #pm2 delete all

