name: Deploy Strapi Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          npm: 'latest'

      - name: Install Yarn
        run: npm install -g yarn    
     
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update -y
            sudo apt-get install -y nodejs npm git
            sudo npm install -g yarn
            REPO_DIR="/home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp"
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/priyanka-1994/Task-2-Pearthought-StrapiApp.git $REPO_DIR
            else
              cd $REPO_DIR && git pull
          fi
          cd $REPO_DIR
        
          npm run build
          
        
        # Step 6: Display Strapi application URL
      - name: Display Strapi application URL
        run: |
          echo "Strapi application is now running at http://$(hostname -I | cut -d' ' -f1):1337"

