name: Deploy Strapi App to EC2

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90  # Adjust timeout as needed

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for proper git operations

      # Step 2: Set up Node.js and npm
      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure Node.js version is compatible with your project

      # Step 3: Upgrade npm
      - name: Upgrade npm
        run: npm install -g npm@latest

      # Step 4: Install Strapi CLI
      - name: Install Strapi CLI
        run: npm install -g strapi@latest

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            
            REPO_DIR="/home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp"
            
            # Clone or pull the repository
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/priyanka-1994/Task-2-Pearthought-StrapiApp.git $REPO_DIR
            else
              cd $REPO_DIR
              git fetch --all
              git reset --hard origin/main  # Reset to main branch
              git pull origin main
            fi
            
            cd $REPO_DIR
            
            # Install dependencies
            yarn install
            
            # Build the project (adjust as per your project's setup)
            yarn build
            yarn cache clean
            
            # Start the Strapi application with pm2
            cd .
            yarn install
            yarn build
            yarn cache clean
            sudo npm install -g pm2@latest
            pm2 start npm --name "strapi" -- run start
            pm2 save  # Save current processes to be restored on server restart

