name: Deploy Code to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90  # Increase timeout for this specific step
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history

      # Step 2: Set up Node.js and npm
      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
      
      - name: Upgrade npm
        run: npm install -g npm@latest
 
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Strapi CLI
        run: npm install -g strapi@latest
    

      # Step 4: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update -y
            sudo apt upgrade -y
            sudo apt-get install -y nodejs npm
            sudo npm install pm2@latest -g

            # sudo npm install -g yarn@4.0.1

            REPO_DIR="/home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp"

            # Clone or pull the repository
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/priyanka-1994/Task-2-Pearthought-StrapiApp.git $REPO_DIR
            else
              cd $REPO_DIR
              git fetch --all
              git reset --hard origin/main  # Reset to main branch
              git pull origin main
            fi

            
        
            cd $REPO_DIR
            yarn install
            
            sudo npm install -g yarn
            
            # Install dependencies and build (adjust as per your project's setup)
           
            yarn build
            yarn cache clean

            #- name: Ensure the directory is empty
            #run: |
            #if [ -d "new-project" ]; then
            #rm -rf new-project
            #fi
           
           #pm2 start npm --name strapi -- run develop
            pm2 start npm --name "strapi" -- run start
            sudo npm install -g strapi@latest
            #cd $REPO_DIR/new-project && yarn install
            #yarn develop
            # Create and start Strapi app
            # sudo npm install pm2@latest -g
            #sudo npm fund
            #pm2 start npm --name "strapi" -- run develop
            #sudo pm2 save
            
