name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Yarn 
        run: npm install -g yarn

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update -y
            sudo apt-get install -y nodejs npm git

            REPO_DIR="/home/${{ secrets.EC2_USER }}/Task-2-Pearthought-StrapiApp"

            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/priyanka-1994/Task-2-Pearthought-StrapiApp.git $REPO_DIR
            else
              cd $REPO_DIR
              git fetch --all
              git reset --hard origin/main
              git pull origin main
            fi

            cd $REPO_DIR
            # build process
            yarn install && yarn build
            sudo npm install strapi -g
            strapi new new-project --quickstart
            cd new-project
            pm2 start yarn --name "strapi" -- run develop
            pm2 save

