name: Deploy to EC2

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  # or yarn install

    - name: Build Strapi app
      run: npm run build  # or yarn build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}  # default SSH port is 22
        script: |
          cd /path/to/strapi/app
          git pull origin main  # ensure latest code
          npm install --production
          npm run build
          pm2 restart ecosystem.config.js  # or your process manager command


