name: Deploy Strapi Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Node.js and Yarn
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify Node.js version 18
          cache: 'yarn'  # Cache yarn packages to speed up builds

      # Step 3: Install dependencies with Yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      # Step 4: Build Strapi application (if necessary)
      # Adjust this step based on your Strapi setup, if a build step is required
      - name: Build Strapi application
        run: |
          yarn build  # Replace with actual build command if needed

      # Step 5: Start Strapi application
      - name: Start Strapi application
        run: |
          yarn start &

      # Step 6: Display Strapi application URL
      - name: Display Strapi application URL
        run: |
          echo "Strapi application is now running at http://$(hostname -I | cut -d' ' -f1):1337"

