name: Deploying Strapi App on EC2 Using Github Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Upgrade npm
      run: npm install -g npm@latest
            
    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10    
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USER }}
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        script: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo apt-get update -y
            sudo apt-get install -y nodejs npm git
            git clone https://github.com/priyanka-1994/Task-2-Pearthought-StrapiApp.git
            cd /home/ubuntu/Task-2-Pearthought-StrapiApp
            yarn install
            cd priya-strapi-app-task-2
            yarn build
            yarn install
            yarn develop
          EOF

    - name: Success
      if: success()
      run: echo "Deployment successfull!"

    - name: Alerting About Failure
      if: failure()
      run: echo "Deployment failed!"      
    

